(require 'markdown-mode)
(require 'tempel)
(require 'lsp-bridge)

(setq lsp-bridge-org-babel-lang-list nil)
(setq lsp-bridge-enable-org-babel t)
(setq lsp-bridge-enable-auto-format-code nil)
(setq acm-enable-tabnine nil)
(setq acm-enable-yas nil)
(setq acm-enable-preview t)
(setq acm-enable-tempel nil)
(setq lsp-bridge-enable-log nil)
(setq lsp-bridge-python-command "~/miniconda3/bin/python3")

(setq lsp-bridge-python-lsp-server 'pyright)
(global-lsp-bridge-mode)
(provide 'init-lspbridge)
